In [391]:
import pandas as pd
import urllib.request
import requests
import re

In [392]:
# update url from state election results website

url = "https://electionresultsfiles.sos.mn.gov/20240305/PNPStatewide.txt"

In [393]:
# read in data in .txt format

response = requests.get(url)
data = response.text
data = data.replace('\r', '')
data = data.split('\n')

data

['MN;;;0100;U.S. Presidential Nominee;;0303;Ron DeSantis;;;R;4100;4100;4086;1.21;337731',
 'MN;;;0100;U.S. Presidential Nominee;;0304;Nikki Haley;;;R;4100;4100;97195;28.78;337731',
 'MN;;;0100;U.S. Presidential Nominee;;0302;Vivek Ramaswamy;;;R;4100;4100;1471;0.44;337731',
 'MN;;;0100;U.S. Presidential Nominee;;0301;Donald J. Trump;;;R;4100;4100;232819;68.94;337731',
 'MN;;;0100;U.S. Presidential Nominee;;0305;Chris Christie;;;R;4100;4100;1436;0.43;337731',
 'MN;;;0100;U.S. Presidential Nominee;;0306;Write-In;;;R;4100;4100;724;0.21;337731',
 'MN;;;0100;U.S. Presidential Nominee;;0404;Uncommitted;;;DFL;4100;4100;45910;18.79;244290',
 'MN;;;0100;U.S. Presidential Nominee;;0411;Write-In;;;DFL;4100;4100;1996;0.82;244290',
 'MN;;;0100;U.S. Presidential Nominee;;0402;Joseph R Biden Jr;;;DFL;4100;4100;171255;70.10;244290',
 'MN;;;0100;U.S. Presidential Nominee;;0403;Eban Cambridge;;;DFL;4100;4100;239;0.10;244290',
 'MN;;;0100;U.S. Presidential Nominee;;0408;Gabriel Cornejo;;;DFL;4100;4100;330;0.14;244290',
 'MN;;;0100;U.S. Presidential Nominee;;0407;Frankie Lozada;;;DFL;4100;4100;296;0.12;244290',
 'MN;;;0100;U.S. Presidential Nominee;;0401;Jason Palmer;;;DFL;4100;4100;771;0.32;244290',
 'MN;;;0100;U.S. Presidential Nominee;;0410;Armando "Mando" Perez-Serrato;;;DFL;4100;4100;372;0.15;244290',
 'MN;;;0100;U.S. Presidential Nominee;;0406;Dean Phillips;;;DFL;4100;4100;18964;7.76;244290',
 'MN;;;0100;U.S. Presidential Nominee;;0409;Cenk Uygur;;;DFL;4100;4100;695;0.28;244290',
 'MN;;;0100;U.S. Presidential Nominee;;0405;Marianne Williamson;;;DFL;4100;4100;3462;1.42;244290',
 'MN;;;0100;U.S. Presidential Nominee;;0604;Edward Forchion;;;LMN;4100;4100;171;6.45;2650',
 'MN;;;0100;U.S. Presidential Nominee;;0602;Krystal Gabel;;;LMN;4100;4100;762;28.75;2650',
 'MN;;;0100;U.S. Presidential Nominee;;0603;Dennis Schuller;;;LMN;4100;4100;461;17.40;2650',
 'MN;;;0100;U.S. Presidential Nominee;;0601;Vermin Supreme;;;LMN;4100;4100;396;14.94;2650',
 'MN;;;0100;U.S. Presidential Nominee;;0606;Write-In;;;LMN;4100;4100;490;18.49;2650',
 'MN;;;0100;U.S. Presidential Nominee;;0605;Rudy Reyes;;;LMN;4100;4100;370;13.96;2650',
 '']

In [394]:
# save as .txt format
with open('results.txt', 'w') as f:
    for line in data:
        f.write(line)
        f.write('\n')

In [395]:
# open in pandas as csv format

df = pd.read_csv("results.txt",delimiter = ';',header=None,)
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,MN,NaN,NaN,100,U.S. Presidential Nominee,NaN,303,Ron DeSantis,NaN,NaN,R,4100,4100,4086,1.21,337731
1,MN,NaN,NaN,100,U.S. Presidential Nominee,NaN,304,Nikki Haley,NaN,NaN,R,4100,4100,97195,28.78,337731
2,MN,NaN,NaN,100,U.S. Presidential Nominee,NaN,302,Vivek Ramaswamy,NaN,NaN,R,4100,4100,1471,0.44,337731
3,MN,NaN,NaN,100,U.S. Presidential Nominee,NaN,301,Donald J. Trump,NaN,NaN,R,4100,4100,232819,68.94,337731
4,MN,NaN,NaN,100,U.S. Presidential Nominee,NaN,305,Chris Christie,NaN,NaN,R,4100,4100,1436,0.43,337731

In [396]:
# add column names

df.columns = [
    'State',
	'County ID (if applicable)',
	'Precinct name (if applicable)',
	'Office ID',
	'Office Name', 
	'District*',
	'Candidate Order Code',
	'Candidate Name (First/Last/Suffix all in one field)',
	'Suffix (not used)',
	'Incumbent Code (not used)',
	'Party Abbreviation',
	'Number of Precincts reporting',
	'Total number of precincts voting for the office',
	'Votes for Candidate',
	'Percentage of Votes for Candidate out of Total Votes for Office',
	'Total number of votes for Office in area'
]

In [397]:
# MAKE SOME CHANGES TO THE COLUMN NAMES

df['Candidate Name (First/Last/Suffix all in one field)'] = df['Candidate Name (First/Last/Suffix all in one field)'].str.replace("Write-In","Write-in")


df.rename(columns={"Candidate Name (First/Last/Suffix all in one field)": "Candidate", "Votes for Candidate": "Votes", "Percentage of Votes for Candidate out of Total Votes for Office": "Percentage"}, inplace=True)

In [398]:
df.head(2)

,State,County ID (if applicable),Precinct name (if applicable),Office ID,Office Name,District*,Candidate Order Code,Candidate,Suffix (not used),Incumbent Code (not used),Party Abbreviation,Number of Precincts reporting,Total number of precincts voting for the office,Votes,Percentage,Total number of votes for Office in area
0,MN,NaN,NaN,100,U.S. Presidential Nominee,NaN,303,Ron DeSantis,NaN,NaN,R,4100,4100,4086,1.21,337731
1,MN,NaN,NaN,100,U.S. Presidential Nominee,NaN,304,Nikki Haley,NaN,NaN,R,4100,4100,97195,28.78,337731

In [399]:
df.to_csv("data/results.csv",index=False)

### Republican Primary Race Data

In [400]:
# select a subset of data for St Paul city council race
GOP = df[df['Party Abbreviation'].str.contains('R')]
GOP

,State,County ID (if applicable),Precinct name (if applicable),Office ID,Office Name,District*,Candidate Order Code,Candidate,Suffix (not used),Incumbent Code (not used),Party Abbreviation,Number of Precincts reporting,Total number of precincts voting for the office,Votes,Percentage,Total number of votes for Office in area
0,MN,NaN,NaN,100,U.S. Presidential Nominee,NaN,303,Ron DeSantis,NaN,NaN,R,4100,4100,4086,1.21,337731
1,MN,NaN,NaN,100,U.S. Presidential Nominee,NaN,304,Nikki Haley,NaN,NaN,R,4100,4100,97195,28.78,337731
2,MN,NaN,NaN,100,U.S. Presidential Nominee,NaN,302,Vivek Ramaswamy,NaN,NaN,R,4100,4100,1471,0.44,337731
3,MN,NaN,NaN,100,U.S. Presidential Nominee,NaN,301,Donald J. Trump,NaN,NaN,R,4100,4100,232819,68.94,337731
4,MN,NaN,NaN,100,U.S. Presidential Nominee,NaN,305,Chris Christie,NaN,NaN,R,4100,4100,1436,0.43,337731
5,MN,NaN,NaN,100,U.S. Presidential Nominee,NaN,306,Write-in,NaN,NaN,R,4100,4100,724,0.21,337731

In [401]:
# Select all columns needed for graphic

GOP = GOP[['Candidate','Votes','Percentage']]

In [402]:
GOP.head()

         Candidate   Votes  Percentage
0     Ron DeSantis    4086        1.21
1      Nikki Haley   97195       28.78
2  Vivek Ramaswamy    1471        0.44
3  Donald J. Trump  232819       68.94
4   Chris Christie    1436        0.43

In [403]:
GOP.to_csv("data/GOP.csv",index=False)

## DFL data

In [404]:
# select a subset of data for DFL

DFL = df[df['Party Abbreviation'].str.contains('DFL')]
DFL

,State,County ID (if applicable),Precinct name (if applicable),Office ID,Office Name,District*,Candidate Order Code,Candidate,Suffix (not used),Incumbent Code (not used),Party Abbreviation,Number of Precincts reporting,Total number of precincts voting for the office,Votes,Percentage,Total number of votes for Office in area
6,MN,NaN,NaN,100,U.S. Presidential Nominee,NaN,404,Uncommitted,NaN,NaN,DFL,4100,4100,45910,18.79,244290
7,MN,NaN,NaN,100,U.S. Presidential Nominee,NaN,411,Write-in,NaN,NaN,DFL,4100,4100,1996,0.82,244290
8,MN,NaN,NaN,100,U.S. Presidential Nominee,NaN,402,Joseph R Biden Jr,NaN,NaN,DFL,4100,4100,171255,70.10,244290
9,MN,NaN,NaN,100,U.S. Presidential Nominee,NaN,403,Eban Cambridge,NaN,NaN,DFL,4100,4100,239,0.10,244290
10,MN,NaN,NaN,100,U.S. Presidential Nominee,NaN,408,Gabriel Cornejo,NaN,NaN,DFL,4100,4100,330,0.14,244290
11,MN,NaN,NaN,100,U.S. Presidential Nominee,NaN,407,Frankie Lozada,NaN,NaN,DFL,4100,4100,296,0.12,244290
12,MN,NaN,NaN,100,U.S. Presidential Nominee,NaN,401,Jason Palmer,NaN,NaN,DFL,4100,4100,771,0.32,244290
13,MN,NaN,NaN,100,U.S. Presidential Nominee,NaN,410,"Armando ""Mando"" Perez-Serrato",NaN,NaN,DFL,4100,4100,372,0.15,244290
14,MN,NaN,NaN,100,U.S. Presidential Nominee,NaN,406,Dean Phillips,NaN,NaN,DFL,4100,4100,18964,7.76,244290
15,MN,NaN,NaN,100,U.S. Presidential Nominee,NaN,409,Cenk Uygur,NaN,NaN,DFL,4100,4100,695,0.28,244290
16,MN,NaN,NaN,100,U.S. Presidential Nominee,NaN,405,Marianne Williamson,NaN,NaN,DFL,4100,4100,3462,1.42,244290

In [405]:
DFL = DFL[['Candidate','Votes','Percentage']]

DFL.head()

            Candidate   Votes  Percentage
6         Uncommitted   45910       18.79
7            Write-in    1996        0.82
8   Joseph R Biden Jr  171255       70.10
9      Eban Cambridge     239        0.10
10    Gabriel Cornejo     330        0.14

In [406]:

DFL.to_csv("data/DFL.csv",index=False)

### LMN Results

In [407]:
# select a subset of data for LMN

LMN = df[df['Party Abbreviation'].str.contains('LMN')]
LMN

,State,County ID (if applicable),Precinct name (if applicable),Office ID,Office Name,District*,Candidate Order Code,Candidate,Suffix (not used),Incumbent Code (not used),Party Abbreviation,Number of Precincts reporting,Total number of precincts voting for the office,Votes,Percentage,Total number of votes for Office in area
17,MN,NaN,NaN,100,U.S. Presidential Nominee,NaN,604,Edward Forchion,NaN,NaN,LMN,4100,4100,171,6.45,2650
18,MN,NaN,NaN,100,U.S. Presidential Nominee,NaN,602,Krystal Gabel,NaN,NaN,LMN,4100,4100,762,28.75,2650
19,MN,NaN,NaN,100,U.S. Presidential Nominee,NaN,603,Dennis Schuller,NaN,NaN,LMN,4100,4100,461,17.40,2650
20,MN,NaN,NaN,100,U.S. Presidential Nominee,NaN,601,Vermin Supreme,NaN,NaN,LMN,4100,4100,396,14.94,2650
21,MN,NaN,NaN,100,U.S. Presidential Nominee,NaN,606,Write-in,NaN,NaN,LMN,4100,4100,490,18.49,2650
22,MN,NaN,NaN,100,U.S. Presidential Nominee,NaN,605,Rudy Reyes,NaN,NaN,LMN,4100,4100,370,13.96,2650

In [408]:
LMN = LMN[['Candidate','Votes','Percentage']]

In [409]:

LMN.to_csv("data/LMN.csv",index=False)

### Precincts reported

In [410]:
progress = df[['Number of Precincts reporting','Total number of precincts voting for the office']].head(1)
progress['pct'] = progress['Number of Precincts reporting'] / progress['Total number of precincts voting for the office']
progress['unreported'] = 1-progress['pct']
progress

,Number of Precincts reporting,Total number of precincts voting for the office,pct,unreported
0,4100,4100,1.0,0.0

In [411]:
progress.to_json("data/progress.json",index=False)