In [1]:
import pandas as pd
import urllib.request
import requests
import re

In [2]:
# update url from state election results website

url = "https://electionresultsfiles.sos.mn.gov/20250812/local.txt"

In [3]:
# read in data in .txt format

response = requests.get(url)
data = response.text
data = data.replace('\r', '')
data = data.split('\n')

data

['MN;;;2801;CITY QUESTION 1 (Clarkfield);11656;9001;YES;;;NP;1;1;708;69.62;1017',
 'MN;;;2801;CITY QUESTION 1 (Clarkfield);11656;9002;NO;;;NP;1;1;309;30.38;1017',
 'MN;;;1010;Council Member At Large (Duluth) (Elect 2);17000;9001;Jordon Johnson;;;NP;34;34;19762;23.21;85135',
 'MN;;;1010;Council Member At Large (Duluth) (Elect 2);17000;9002;Terese Tomanek;;;NP;34;34;17738;20.84;85135',
 'MN;;;1010;Council Member At Large (Duluth) (Elect 2);17000;9003;Zachary Davis Moder;;;NP;34;34;15046;17.67;85135',
 'MN;;;1010;Council Member At Large (Duluth) (Elect 2);17000;9004;Derek Medved;;;NP;34;34;16874;19.82;85135',
 'MN;;;1010;Council Member At Large (Duluth) (Elect 2);17000;9005;Asher Estrin-Haire;;;NP;34;34;15715;18.46;85135',
 'MN;;;1022;Council Member District 2 (Duluth);17000;9001;Diane Desotelle;;;NP;6;6;2894;34.82;8312',
 'MN;;;1022;Council Member District 2 (Duluth);17000;9002;Christopher Adatte;;;NP;6;6;2733;32.88;8312',
 'MN;;;1022;Council Member District 2 (Duluth);17000;9003;Pierre Tournier;;;NP;6;6;2685;32.30;8312',
 'MN;;;2801;CITY QUESTION 1 (International Falls);31040;9001;YES;;;NP;3;3;1711;46.51;3679',
 'MN;;;2801;CITY QUESTION 1 (International Falls);31040;9002;NO;;;NP;3;3;1968;53.49;3679',
 'MN;;;1001;Special Election for Mayor (Isanti);31328;9001;Jeff Johnson;;;NP;2;2;843;24.39;3456',
 'MN;;;1001;Special Election for Mayor (Isanti);31328;9002;Luke Merrill;;;NP;2;2;1004;29.05;3456',
 'MN;;;1001;Special Election for Mayor (Isanti);31328;9099;WRITE-IN;;;NP;2;2;1609;46.56;3456',
 'MN;;;2131;Special Election for Council Member Ward 4 First Choice (St. Paul);58000;9001;Cole Hanson;;;NP;13;13;8325;22.73;36627',
 'MN;;;2131;Special Election for Council Member Ward 4 First Choice (St. Paul);58000;9002;Chauntyll Allen;;;NP;13;13;7446;20.33;36627',
 'MN;;;2131;Special Election for Council Member Ward 4 First Choice (St. Paul);58000;9003;Molly Coleman;;;NP;13;13;7857;21.45;36627',
 'MN;;;2131;Special Election for Council Member Ward 4 First Choice (St. Paul);58000;9004;Carolyn Will;;;NP;13;13;6647;18.15;36627',
 'MN;;;2131;Special Election for Council Member Ward 4 First Choice (St. Paul);58000;9099;WRITE-IN;;;NP;13;13;6352;17.34;36627',
 'MN;;;1012;Special Election for Council Member At Large (Two Harbors);65956;9001;Laura Osbakken Goutermont;;;NP;4;4;2059;36.85;5588',
 'MN;;;1012;Special Election for Council Member At Large (Two Harbors);65956;9002;Donna Heil;;;NP;4;4;1744;31.21;5588',
 'MN;;;1012;Special Election for Council Member At Large (Two Harbors);65956;9099;WRITE-IN;;;NP;4;4;1785;31.94;5588',
 'MN;;;1001;Mayor (White Bear Lake);69970;9001;Mary Nicklawske;;;NP;6;6;1745;22.56;7735',
 'MN;;;1001;Mayor (White Bear Lake);69970;9002;Matthew Schoenthaler;;;NP;6;6;3324;42.97;7735',
 'MN;;;1001;Mayor (White Bear Lake);69970;9003;Stephen Laliberte;;;NP;6;6;2666;34.47;7735',
 '']

In [4]:
# save as .txt format
with open('results.txt', 'w') as f:
    for line in data:
        f.write(line)
        f.write('\n')

In [5]:
# open in pandas as csv format

df = pd.read_csv("results.txt",delimiter = ';',header=None,)
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,MN,NaN,NaN,2801,CITY QUESTION 1 (Clarkfield),11656,9001,YES,NaN,NaN,NP,1,1,708,69.62,1017
1,MN,NaN,NaN,2801,CITY QUESTION 1 (Clarkfield),11656,9002,NO,NaN,NaN,NP,1,1,309,30.38,1017
2,MN,NaN,NaN,1010,Council Member At Large (Duluth) (Elect 2),17000,9001,Jordon Johnson,NaN,NaN,NP,34,34,19762,23.21,85135
3,MN,NaN,NaN,1010,Council Member At Large (Duluth) (Elect 2),17000,9002,Terese Tomanek,NaN,NaN,NP,34,34,17738,20.84,85135
4,MN,NaN,NaN,1010,Council Member At Large (Duluth) (Elect 2),17000,9003,Zachary Davis Moder,NaN,NaN,NP,34,34,15046,17.67,85135

In [6]:
# add column names

df.columns = [
    'State',
	'County ID (if applicable)',
	'Precinct name (if applicable)',
	'Office ID',
	'Office Name', 
	'District*',
	'Candidate Order Code',
	'Candidate Name (First/Last/Suffix all in one field)',
	'Suffix (not used)',
	'Incumbent Code (not used)',
	'Party Abbreviation',
	'Number of Precincts reporting',
	'Total number of precincts voting for the office',
	'Votes for Candidate',
	'Percentage of Votes for Candidate out of Total Votes for Office',
	'Total number of votes for Office in area'
]

In [7]:
# MAKE SOME CHANGES TO THE COLUMN NAMES

df['Candidate Name (First/Last/Suffix all in one field)'] = df['Candidate Name (First/Last/Suffix all in one field)'].str.replace("Write-In","Write-in")


df.rename(columns={"Candidate Name (First/Last/Suffix all in one field)": "Candidate", "Votes for Candidate": "Votes", "Percentage of Votes for Candidate out of Total Votes for Office": "Percentage"}, inplace=True)

In [8]:
df.head(2)

,State,County ID (if applicable),Precinct name (if applicable),Office ID,Office Name,District*,Candidate Order Code,Candidate,Suffix (not used),Incumbent Code (not used),Party Abbreviation,Number of Precincts reporting,Total number of precincts voting for the office,Votes,Percentage,Total number of votes for Office in area
0,MN,NaN,NaN,100,U.S. Presidential Nominee,NaN,303,Ron DeSantis,NaN,NaN,R,4100,4100,4084,1.21,337762
1,MN,NaN,NaN,100,U.S. Presidential Nominee,NaN,304,Nikki Haley,NaN,NaN,R,4100,4100,97184,28.77,337762

In [9]:
df.to_csv("data/results.csv",index=False)

### Republican Primary Race Data

In [10]:
# select a subset of data for St Paul city council race
GOP = df[df['Party Abbreviation'].str.contains('R')]
GOP

,State,County ID (if applicable),Precinct name (if applicable),Office ID,Office Name,District*,Candidate Order Code,Candidate,Suffix (not used),Incumbent Code (not used),Party Abbreviation,Number of Precincts reporting,Total number of precincts voting for the office,Votes,Percentage,Total number of votes for Office in area
0,MN,NaN,NaN,100,U.S. Presidential Nominee,NaN,303,Ron DeSantis,NaN,NaN,R,4100,4100,4084,1.21,337762
1,MN,NaN,NaN,100,U.S. Presidential Nominee,NaN,304,Nikki Haley,NaN,NaN,R,4100,4100,97184,28.77,337762
2,MN,NaN,NaN,100,U.S. Presidential Nominee,NaN,302,Vivek Ramaswamy,NaN,NaN,R,4100,4100,1470,0.44,337762
3,MN,NaN,NaN,100,U.S. Presidential Nominee,NaN,301,Donald J. Trump,NaN,NaN,R,4100,4100,232873,68.95,337762
4,MN,NaN,NaN,100,U.S. Presidential Nominee,NaN,305,Chris Christie,NaN,NaN,R,4100,4100,1431,0.42,337762
5,MN,NaN,NaN,100,U.S. Presidential Nominee,NaN,306,Write-in,NaN,NaN,R,4100,4100,720,0.21,337762

In [11]:
# Select all columns needed for graphic

GOP = GOP[['Candidate','Votes','Percentage']]

In [12]:
GOP.head()

         Candidate   Votes  Percentage
0     Ron DeSantis    4084        1.21
1      Nikki Haley   97184       28.77
2  Vivek Ramaswamy    1470        0.44
3  Donald J. Trump  232873       68.95
4   Chris Christie    1431        0.42

In [13]:
GOP.to_csv("data/GOP.csv",index=False)

## DFL data

In [14]:
# select a subset of data for DFL

DFL = df[df['Party Abbreviation'].str.contains('DFL')]
DFL

,State,County ID (if applicable),Precinct name (if applicable),Office ID,Office Name,District*,Candidate Order Code,Candidate,Suffix (not used),Incumbent Code (not used),Party Abbreviation,Number of Precincts reporting,Total number of precincts voting for the office,Votes,Percentage,Total number of votes for Office in area
6,MN,NaN,NaN,100,U.S. Presidential Nominee,NaN,409,Cenk Uygur,NaN,NaN,DFL,4100,4100,692,0.28,244293
7,MN,NaN,NaN,100,U.S. Presidential Nominee,NaN,405,Marianne Williamson,NaN,NaN,DFL,4100,4100,3459,1.42,244293
8,MN,NaN,NaN,100,U.S. Presidential Nominee,NaN,402,Joseph R Biden Jr,NaN,NaN,DFL,4100,4100,171279,70.11,244293
9,MN,NaN,NaN,100,U.S. Presidential Nominee,NaN,403,Eban Cambridge,NaN,NaN,DFL,4100,4100,235,0.10,244293
10,MN,NaN,NaN,100,U.S. Presidential Nominee,NaN,408,Gabriel Cornejo,NaN,NaN,DFL,4100,4100,323,0.13,244293
11,MN,NaN,NaN,100,U.S. Presidential Nominee,NaN,407,Frankie Lozada,NaN,NaN,DFL,4100,4100,290,0.12,244293
12,MN,NaN,NaN,100,U.S. Presidential Nominee,NaN,401,Jason Palmer,NaN,NaN,DFL,4100,4100,769,0.31,244293
13,MN,NaN,NaN,100,U.S. Presidential Nominee,NaN,410,"Armando ""Mando"" Perez-Serrato",NaN,NaN,DFL,4100,4100,372,0.15,244293
14,MN,NaN,NaN,100,U.S. Presidential Nominee,NaN,406,Dean Phillips,NaN,NaN,DFL,4100,4100,18960,7.76,244293
15,MN,NaN,NaN,100,U.S. Presidential Nominee,NaN,404,Uncommitted,NaN,NaN,DFL,4100,4100,45914,18.79,244293
16,MN,NaN,NaN,100,U.S. Presidential Nominee,NaN,411,Write-in,NaN,NaN,DFL,4100,4100,2000,0.82,244293

In [15]:
DFL = DFL[['Candidate','Votes','Percentage']]

DFL.head()

              Candidate   Votes  Percentage
6            Cenk Uygur     692        0.28
7   Marianne Williamson    3459        1.42
8     Joseph R Biden Jr  171279       70.11
9        Eban Cambridge     235        0.10
10      Gabriel Cornejo     323        0.13

In [16]:

DFL.to_csv("data/DFL.csv",index=False)

### LMN Results

In [17]:
# select a subset of data for LMN

LMN = df[df['Party Abbreviation'].str.contains('LMN')]
LMN

,State,County ID (if applicable),Precinct name (if applicable),Office ID,Office Name,District*,Candidate Order Code,Candidate,Suffix (not used),Incumbent Code (not used),Party Abbreviation,Number of Precincts reporting,Total number of precincts voting for the office,Votes,Percentage,Total number of votes for Office in area
17,MN,NaN,NaN,100,U.S. Presidential Nominee,NaN,604,Edward Forchion,NaN,NaN,LMN,4100,4100,168,6.38,2633
18,MN,NaN,NaN,100,U.S. Presidential Nominee,NaN,602,Krystal Gabel,NaN,NaN,LMN,4100,4100,760,28.86,2633
19,MN,NaN,NaN,100,U.S. Presidential Nominee,NaN,603,Dennis Schuller,NaN,NaN,LMN,4100,4100,459,17.43,2633
20,MN,NaN,NaN,100,U.S. Presidential Nominee,NaN,601,Vermin Supreme,NaN,NaN,LMN,4100,4100,397,15.08,2633
21,MN,NaN,NaN,100,U.S. Presidential Nominee,NaN,606,Write-in,NaN,NaN,LMN,4100,4100,484,18.38,2633
22,MN,NaN,NaN,100,U.S. Presidential Nominee,NaN,605,Rudy Reyes,NaN,NaN,LMN,4100,4100,365,13.86,2633

In [18]:
LMN = LMN[['Candidate','Votes','Percentage']]

In [19]:

LMN.to_csv("data/LMN.csv",index=False)

### Precincts reported

In [20]:
progress = df[['Number of Precincts reporting','Total number of precincts voting for the office']].head(1)
progress['pct'] = progress['Number of Precincts reporting'] / progress['Total number of precincts voting for the office']
progress['unreported'] = 1-progress['pct']
progress

,Number of Precincts reporting,Total number of precincts voting for the office,pct,unreported
0,4100,4100,1.0,0.0

In [21]:
progress.to_json("data/progress.json",index=False)